# Generated by Django 5.1.5 on 2025-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_category_options_project_invite_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattachment",
            name="content_type",
            field=models.CharField(
                blank=True, default="application/octet-stream", max_length=100
            ),
        ),
    ]
