# Generated by Django 5.1.5 on 2025-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_taskattachment_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="task_attachments/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
    ]
