# Generated by Django 5.1.5 on 2025-01-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_attachment_alter_task_due_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="project",
            name="invite_token",
        ),
        migrations.RemoveField(
            model_name="task",
            name="attachment",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Urgent")],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "In Review"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
