# Generated by Django 5.1.5 on 2025-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_category_estimated_time_comment_mentioned_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="mentioned_users",
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload a file related to this task (max 5MB)",
                max_length=255,
                null=True,
                upload_to="task_attachments/%Y/%m/",
            ),
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
    ]
